# Generated by Django 2.2.1 on 2020-10-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0006_auto_20201008_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=32, verbose_name='订单编号')),
                ('order_status', models.IntegerField(default=0, verbose_name='订单状态')),
                ('type_number', models.IntegerField(default=0, verbose_name='商品数量')),
                ('total_price', models.FloatField(verbose_name='订单总金额')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.QUser', verbose_name='买家')),
            ],
            options={
                'db_table': 'placeorder',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名字')),
                ('goods_price', models.FloatField(verbose_name='商品单价')),
                ('goods_num', models.IntegerField(verbose_name='商品数量')),
                ('goods_picture', models.CharField(max_length=64, verbose_name='商品图片')),
                ('goods_total', models.FloatField(verbose_name='商品小计')),
                ('goods_status', models.IntegerField(verbose_name='商品状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.PlaceOrder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Store')),
            ],
            options={
                'db_table': 'orderinfo',
            },
        ),
    ]
