# Generated by Django 2.2.1 on 2020-09-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nick_name', models.CharField(max_length=32, verbose_name='昵称')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别(0-女，1-男)')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(verbose_name='地址')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'db_table': 'storeuser',
            },
        ),
    ]
