# Generated by Django 2.2.1 on 2020-09-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别(0-女，1-男)'),
        ),
    ]
