# Generated by Django 2.2.1 on 2020-09-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20200924_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='address',
            field=models.TextField(null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别(0-女，1-男)'),
        ),
    ]
