# Generated by Django 2.2.1 on 2020-09-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32, verbose_name='商品名')),
                ('g_number', models.IntegerField(verbose_name='商品编号')),
                ('g_price', models.FloatField(verbose_name='单价')),
                ('g_safe_date', models.IntegerField(verbose_name='保质期')),
                ('g_description', models.TextField(verbose_name='描述')),
                ('g_picutre', models.ImageField(upload_to='images', verbose_name='商品图片')),
                ('g_num', models.IntegerField(verbose_name='商品库存')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=32, verbose_name='类型名')),
                ('t_description', models.TextField(verbose_name='类型描述')),
                ('t_img', models.CharField(max_length=64, verbose_name='类型图片')),
            ],
            options={
                'db_table': 'goodstype',
            },
        ),
        migrations.CreateModel(
            name='QUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(default=1, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('picture', models.ImageField(default='1.jpg', upload_to='images', verbose_name='头像')),
                ('address', models.TextField(default='', verbose_name='地址')),
                ('usertype', models.IntegerField(default=0, verbose_name='用户类型')),
            ],
            options={
                'db_table': 'quser',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=32, verbose_name='商铺名')),
                ('s_logo', models.CharField(max_length=64, verbose_name='商铺logo')),
                ('s_address', models.TextField(verbose_name='商铺地址')),
                ('s_description', models.TextField(verbose_name='商铺描述')),
                ('s_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Store.QUser')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=32, verbose_name='图片路径')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Goods')),
            ],
            options={
                'db_table': 'goodsimg',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='g_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Store'),
        ),
        migrations.AddField(
            model_name='goods',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.GoodsType'),
        ),
    ]
