# Generated by Django 2.2.1 on 2020-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='s_changed',
            field=models.CharField(max_length=32, verbose_name='测试1'),
        ),
    ]
