# Generated by Django 2.2.1 on 2020-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20201005_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='s_changed',
            field=models.DateTimeField(verbose_name='店铺名修改时间'),
        ),
    ]
