# Generated by Django 2.2.1 on 2020-10-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20201005_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='s_changed',
            new_name='s_changed_datetime',
        ),
    ]
