# Generated by Django 2.2.1 on 2020-10-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20201005_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_number',
            field=models.IntegerField(auto_created=True, verbose_name='商品编号'),
        ),
    ]
