# Generated by Django 2.2.1 on 2020-10-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20201008_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_number',
            field=models.IntegerField(verbose_name='商品编号'),
        ),
    ]
